fake = false
log_level = "INFO"
zmq_auto_kill_timedelta = 5

[rcms]
host = "http://172.18.2.72:8182"
username = "lll"
password = "Hik@123++"

[redis]
host = "127.0.0.1"
port = 6379
db = 2

[web]
host = "0.0.0.0"
port = 8000